// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable
namespace MagistralDevice.DataClasses
{
  public enum AccessLevel
  {
    Sys,
    Usr
  }
}
#pragma warning restore
