// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------

// ReSharper disable UnusedMember.Global
#pragma warning disable
namespace MagistralDevice.DataClasses
{
  public enum CommandNames
  {
    GET_ATTRIBUTES
  }
}
#pragma warning restore
