// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
// ReSharper disable PossibleNullReferenceException

using System;
using System.Diagnostics;
using System.IO;
using System.Xml;
using System.Xml.Serialization;

// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global
// ReSharper disable AutoPropertyCanBeMadeGetOnly.Global

#pragma warning disable
namespace MagistralDevice.DataClasses
{
  [XmlRoot(ElementName = "DeviceData")]
  // ReSharper disable once InconsistentNaming
  public sealed class dxDeviceData
  {
    /// <summary>
    ///   DeviceData class constructor
    /// </summary>
    // ReSharper disable InconsistentNaming
    public dxDeviceData() {
      Parameters = new dxParameterList();
      Attributes = new dxDeviceAttributes();
    }

    public dxDeviceAttributes Attributes
    {
      get;
      set;
    }

    public dxParameterList Parameters
    {
      get;
      set;
    }

    private static XmlSerializer Serializer
    {
      get
      {
        if( serializer == null ) {
          serializer = new XmlSerializerFactory().CreateSerializer(typeof(dxDeviceData));
          serializer.UnknownNode += delegate(object sender, XmlNodeEventArgs e) {
                                      Debug.WriteLine("[Unknown Node] Ln {0} Col {1} Object: {2} LocalName {3}, NodeName: {4}", e.LineNumber, e.LinePosition, e.ObjectBeingDeserialized.GetType().FullName, e.LocalName, e.Name);
                                    };
          serializer.UnknownElement += delegate(object sender, XmlElementEventArgs e) {
                                         Debug.WriteLine("[Unknown Element  ] Ln {0} Col {1} Object : {2} ExpectedElements {3}, Element : {4}",
                                                         e.LineNumber,
                                                         e.LinePosition,
                                                         e.ObjectBeingDeserialized.GetType().FullName,
                                                         e.ExpectedElements,
                                                         e.Element.InnerXml);
                                       };
          serializer.UnknownAttribute += delegate(object sender, XmlAttributeEventArgs e) {
                                           Debug.WriteLine("[Unknown Attribute] Ln {0} Col {1} Object : {2} LocalName {3}, Text : {4}",
                                                           e.LineNumber,
                                                           e.LinePosition,
                                                           e.ObjectBeingDeserialized.GetType().FullName,
                                                           e.ExpectedAttributes,
                                                           e.Attr.Name);
                                         };
        }

        return serializer;
      }
    }

    /// <summary>
    ///   Serializes current dxDeviceData object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public bool SaveToFile(string fileName, out Exception exception) {
      exception = null;
      try {
        SaveToFile(fileName);
        return true;
      }
      catch( Exception e ) {
        exception = e;
        return false;
      }
    }

    public void SaveToFile(string fileName) {
      StreamWriter streamWriter = null;
      try {
        string xmlString = Serialize();
        FileInfo xmlFile = new FileInfo(fileName ?? throw new ArgumentNullException(nameof(fileName)));
        streamWriter = xmlFile.CreateText();
        streamWriter.WriteLine(xmlString);
        streamWriter.Close();
      }
      finally {
        streamWriter?.Dispose();
      }
    }

    /// <summary>
    ///   Deserializes xml markup from file into an dxDeviceData object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output dxDeviceData object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, out dxDeviceData obj, out Exception exception) {
      exception = null;
      obj = default(dxDeviceData);
      try {
        obj = LoadFromFile(fileName);
        return true;
      }
      catch( Exception ex ) {
        exception = ex;
        return false;
      }
    }

    public static bool LoadFromFile(string fileName, out dxDeviceData obj) {
      bool result = LoadFromFile(fileName, out obj, out Exception exception);
      if( exception != null ) {
        throw exception;
      }

      return result;
    }

    public static dxDeviceData LoadFromFile(string fileName) {
      FileStream file = null;
      StreamReader sr = null;
      try {
        file = new FileStream(fileName ?? throw new ArgumentNullException(nameof(fileName)), FileMode.Open, FileAccess.Read);
        sr = new StreamReader(file);
        string xmlString = sr.ReadToEnd();
        sr.Close();
        file.Close();
        return Deserialize(xmlString);
      }
      finally {
        file?.Dispose();

        sr?.Dispose();
      }
    }

    #region Clone method

    /// <summary>
    ///   Create a clone of this dxDeviceData object
    /// </summary>
    public dxDeviceData Clone() {
      return(dxDeviceData)MemberwiseClone();
    }

    #endregion

    #region Private fields

    private static XmlSerializer serializer;

    #endregion

    #region Serialize/Deserialize

    /// <summary>
    ///   Serializes current dxDeviceData object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public string Serialize() {
      StreamReader streamReader = null;
      MemoryStream memoryStream = null;
      try {
        memoryStream = new MemoryStream();
        XmlWriterSettings xmlWriterSettings = new XmlWriterSettings
                                              {
                                                  Indent = true,
                                                  IndentChars = "  "
                                              };
        XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
        Serializer.Serialize(xmlWriter, this);
        memoryStream.Seek(0, SeekOrigin.Begin);
        streamReader = new StreamReader(memoryStream);
        return streamReader.ReadToEnd();
      }
      finally {
        streamReader?.Dispose();
        memoryStream?.Dispose();
      }
    }

    /// <summary>
    ///   Deserializes workflow markup into an dxDeviceData object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output dxDeviceData object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out dxDeviceData obj, out Exception exception) {
      exception = null;
      obj = default(dxDeviceData);
      try {
        obj = Deserialize(input);
        return true;
      }
      catch( Exception ex ) {
        exception = ex;
        return false;
      }
    }

    public static bool Deserialize(string input, out dxDeviceData obj) {
      bool result = Deserialize(input, out obj, out Exception exception);
      if( exception != null ) {
        throw exception;
      }

      return result;
    }

    public static dxDeviceData Deserialize(string input) {
      StringReader stringReader = null;
      try {
        stringReader = new StringReader(input ?? throw new ArgumentNullException(nameof(input)));
        return(dxDeviceData)Serializer.Deserialize(XmlReader.Create(stringReader));
      }
      finally {
        stringReader?.Dispose();
      }
    }

    public static dxDeviceData Deserialize(Stream s) {
      return(dxDeviceData)Serializer.Deserialize(s ?? throw new ArgumentNullException(nameof(s)));
    }

    #endregion
  }
}
#pragma warning restore
